# Generated by Django 3.1.2 on 2020-10-31 16:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Rekomender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
