# Generated by Django 3.1.2 on 2020-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('amazon', models.IntegerField(default=0)),
                ('google', models.IntegerField(default=0)),
                ('microsoft', models.IntegerField(default=0)),
                ('krajowa', models.IntegerField(default=0)),
                ('ibm', models.IntegerField(default=0)),
                ('city', models.IntegerField(default=0)),
                ('task', models.IntegerField(default=0)),
            ],
        ),
    ]
